"""Wiki output helpers — write sift ask results to the LLM wiki."""

from __future__ import annotations

import re
from datetime import date, datetime, timezone
from pathlib import Path

WIKI_RAW_DIR = Path.home() / "llm-wiki" / "raw" / "queries"


def slugify(text: str, max_len: int = 60) -> str:
    """Convert text to a wiki-safe filename slug."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_len].rstrip("-")


def clean_answer(answer: str) -> str:
    """Strip thinking/reasoning preamble from a model's answer.

    DeepSeek models emit their internal monologue followed by the
    actual answer, often appended as the very last sentence (even
    within the same paragraph). We extract the final sentence(s)
    that constitute the actual answer.
    """
    # Try paragraph-based first
    paragraphs = [p.strip() for p in answer.split("\n\n") if p.strip()]
    if not paragraphs:
        return answer

    # Meta patterns — sentences that are clearly thinking, not answering
    def is_meta(text):
        return bool(re.match(
            r"^(We are |We need |Let me |I need to |First[ ,]|Thinking|The user |"
            r"Based on |Looking at|Analyzing |The provided |"
            r"Okay,|So, |Hmm|Actually|Wait |The question|"
            r"The context|Given |Now,|Here |I'll |"
            r"We cannot|We must |We should |This means |"
            r"In this |The key |The main |One approach|"
            r"Therefore|Thus,|After |Before |To answer|"
            r"Note that|It is worth|Let's |Lets |"
            r"Finally,|In summary|In conclusion|"
            r"I think|I believe|I can |I will |"
            r"\d+\.\s+\*\*|^[\*\-#])",
            text.strip(), re.IGNORECASE,
        ))

    # Start from the last paragraph and work backwards
    for i in range(len(paragraphs) - 1, -1, -1):
        para = paragraphs[i]
        if not is_meta(para):
            # This paragraph looks like an answer
            return para

        # Try last sentence of meta paragraph (model often appends answer inline)
        # DeepSeek appends without a space: "...sentence.The capital..."
        sentences = re.split(r"(?<=[.!?])\s+(?=[A-Z])|(?<=[.!?])(?=[A-Z])", para)
        if len(sentences) >= 2:
            # Check if the last sentence is a real answer
            last_sent = sentences[-1].strip()
            if not is_meta(last_sent) and len(last_sent) > 5:
                return last_sent

    # All paragraphs are meta — extract the last sentence from the entire text
    all_text = "\n".join(paragraphs)
    all_sentences = re.split(r"(?<=[.!?])\s+(?=[A-Z])|(?<=[.!?])(?=[A-Z])", all_text)
    for j in range(len(all_sentences) - 1, -1, -1):
        s = all_sentences[j].strip()
        if not is_meta(s) and len(s) > 5:
            return s

    # Absolute fallback — return the last paragraph as-is
    return paragraphs[-1]


def write_raw_source(
    title: str,
    slug: str,
    query: str,
    synthesis: str,
    sources: list[str],
) -> str:
    """Write synthesis + sources as an immutable raw-source file.

    Creates ``{WIKI_RAW_DIR}/{slug}.md`` with proper frontmatter.
    If the file already exists, appends a new Update section.
    Returns the absolute path of the written file.
    """
    today = date.today().isoformat()
    now_iso = datetime.now(timezone.utc).isoformat()

    # Build body — use the full synthesis, not a cleaned version
    body = synthesis

    # Build frontmatter
    tag_lines = "  - topic:research"

    frontmatter = f"""---
title: "{title}"
created: {today}
updated: {today}
type: raw-source
tags:
{tag_lines}
source_query: "{query}"
ingested: {today}
"""

    if sources:
        source_lines = "\n".join(
            f'  - url: "{s}"\n    accessed: {today}' for s in sources[:10]
        )
        frontmatter += f"sources:\n{source_lines}\n"

    frontmatter += "---"

    if sources:
        body += "\n\n## Sources\n\n"
        for i, s in enumerate(sources, 1):
            body += f"{i}. {s}\n"

    body += f"\n\n---\n*Generated by sift ask --wiki on {now_iso}*"

    content = f"{frontmatter}\n\n{body}\n"

    # Write
    WIKI_RAW_DIR.mkdir(parents=True, exist_ok=True)
    page_path = WIKI_RAW_DIR / f"{slug}.md"

    # Append if exists (raw sources accumulate updates)
    if page_path.exists():
        existing = page_path.read_text(encoding="utf-8")
        fm_end = existing.find("---", 3)
        if fm_end > 0:
            existing_body = existing[fm_end + 3:].strip()
            body = existing_body + f"\n\n---\n\n## Update - {today}\n\n{body}"
            existing = (
                existing[: fm_end + 3]
                + "\nupdated: " + today + "\n"
                + existing[fm_end + 3:]
            )
            existing = existing[: existing.rfind("---", 3)] + "---\n" + body
            page_path.write_text(existing, encoding="utf-8")
            return str(page_path)

    page_path.write_text(content, encoding="utf-8")
    return str(page_path)


def extract_sources_from_answer(answer: str) -> list[str]:
    """Extract source URLs from the answer text itself."""
    return list(dict.fromkeys(re.findall(r"https?://[^\s\)\]>]+", answer)))
